Repository udistrital/resoluciones_cliente, pull requests merged in 2019-07, with the labels that each got.

#5 Merge entre gaia_dev y cumplidos_cps_pruebas
  .bowerrc
  .drone.yml
  app/scripts/controllers/menu.js
  app/scripts/controllers/seguimientoycontrol/tecnico/aprobacion_ordenador.js
  app/scripts/controllers/seguimientoycontrol/tecnico/aprobacion_supervisor.js
  app/views/seguimientoycontrol/tecnico/aprobacion_ordenador.html
  bower.json
  package-lock.json
Labels: Unificación cliente.

#18 correccion de la lista de resoluciones al momento de generar una diferente a vinculacion
  app/scripts/controllers/vinculacionespecial/resolucion_generacion.js
Labels: bug, enhancement

#20 se agrega el andar el usuario al crearse cualquier resolucion
  app/scripts/controllers/vinculacionespecial/resolucion_generacion.js
Labels: Resoluciones, enhancement
